#!/usr/bin/env bash
### Displays information about subdomains
### $1 = domain | $2 = subdomain
### Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# shellcheck disable=SC2086

if [  $# == 2  ]; then
    var_rec=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
    var_ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
    echo "The subdomain $2 is a $var_rec record and points to $var_ip"
else
    var_rec=$(dig www.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
    var_ip=$(dig www.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
    echo "The subdomain www is a $var_rec record and points to $var_ip"
    var_rec=$(dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
    var_ip=$(dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
    echo "The subdomain lb-01 is a $var_rec record and points to $var_ip"
    var_rec=$(dig web-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
    var_ip=$(dig web-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
    echo "The subdomain web-01 is a $var_rec record and points to $var_ip"
    var_rec=$(dig web-02.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
    var_ip=$(dig web-02.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
    echo "The subdomain web-02 is a $var_rec record and points to $var_ip"
fi

# if [ $# -eq 2 ]
# then
#     RECORD_TYPE=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
#     DESTINATION=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
#     echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
# else
#     var=$1
#     declare -a subs=("www" "lb-01" "web-01" "web-02")
#     for sub in ${subs[@]}; do
# 	RECORD_TYPE=$(dig ${sub}.${var} | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
# 	DESTINATION=$(dig ${sub}.${var} | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
# 	echo "The subdomain $sub is a $RECORD_TYPE record and points to $DESTINATION"
# 	done
# fi
