#!/usr/bin/env bash
### Transfers file from client to server
if [  "$#" == 4  ]; then
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2":./
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
