#!/usr/bin/env bash
### Installs nginx, sets listening to port 80, creates basic index.html
apt-get update -y
apt-get install nginx -y
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx start
