#!/usr/bin/env bash
### Installs nginx, sets listening to port 80, GET request response
apt-get update -y
apt-get install nginx -y
ufw enable -y
ufw allow 'Nginx HTTP'
touch index.html
echo "Holberton School" >> index.html
