#!/usr/bin/env bash
### Redirects /redirect_me page to another page by editing nginx.conf
apt-get update -y
apt-get install nginx -y
ufw enable -y
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx start
