#!/usr/bin/env bash
### Installs nginx, configures index.html, 404 error and 301 redirect

new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"

apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo service nginx start
