#!/usr/bin/env bash
### Display FizzBuzz!
x="1"
while [  $x -lt 101  ]; do
    if ! ((x % 3)) && ! ((x % 5)); then
	echo 'FizzBuzz'
    elif ! ((x % 3)); then
	echo 'Fizz'
    elif ! ((x % 5)); then
	echo 'Buzz'
    else
	echo $x
fi
x=$((x+1))
done
