#!/usr/bin/env bash
### Display numbers up to 20 with case statements
x="1"
while [  $x -lt 21  ]; do
case $x in
    5)
    echo 'bad luck from China'
    ;;
    10)
    echo 'bad luck from Japan'
    ;;
    18)
    echo 'bad luck from Italy'
    ;;
esac
echo $x
x=$((x+1))
done
