#!/usr/bin/env bash
### Display numbers up to 20 with case statements
x="1"
while [  $x -lt 21  ]; do
case $x in
    5)
    echo 'bad luck from China'
    ;;
    10)
    echo 'bad luck from Japan'
    ;;
    18)
    echo 'bad luck from Italy'
    ;;
esac
echo $x
x=$((x+1))
done
# while [  $x -lt 20  ]; do
#     if [  $x == 3   ]; then
# 	echo 'bad luck'
#     elif [ $x == 7  ]; then
# 	echo 'good luck'
#     else
# 	echo 'Holberton School'
#     fi
# x=$((x+1))
# done
