#!/usr/bin/env bash
### Displays directory contents with pre-dash name removed
for filename in *; do
printf %s\\n "$(basename "$filename" | sed -r 's/.*(\-*)-(.*)/\2/')"
done
# for filename in *; do
# echo "$(basename "$filename" | sed -r 's/.*(\-*)-(.*)/\2/')"
# done
